# Generated by Django 4.2.1 on 2024-01-08 16:10

from django.db import migrations, models
import store.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_productimage_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.Validators.validate_file_size]),
        ),
    ]
